README.md, generate_reflection/src/emitter_rust.rs, rbx_dom_weak/src/value.rs, rbx_reflection/src/resolution.rs, rbx_xml/src/deserializer.rs, rbx_xml/src/serializer.rs, rbx_xml/src/types/numbers.rs, rbx_xml/test-files/numbers.rbxmx, rbx_xml/tests/round_trip.rs
Side note, there's a LOT of repetitive code in this codebase. A proc macro would do this wonders.
=> Int64 and Float64

rbx_xml/src/core.rs, rbx_xml/src/deserializer.rs, rbx_xml/src/lib.rs, rbx_xml/src/macros.rs, rbx_xml/src/serializer.rs, rbx_xml/src/test_util.rs, rbx_xml/src/types/binary_string.rs, rbx_xml/src/types/bool.rs, rbx_xml/src/types/cframe.rs, rbx_xml/src/types/colors.rs, rbx_xml/src/types/content.rs, rbx_xml/src/types/enumeration.rs, rbx_xml/src/types/mod.rs, rbx_xml/src/types/numbers.rs, rbx_xml/src/types/physical_properties.rs, rbx_xml/src/types/referent.rs, rbx_xml/src/types/strings.rs, rbx_xml/src/types/udims.rs, rbx_xml/src/types/vectors.rs
Maaan, dealing with whitespace in XML is a huge pain it turns out.
This PR:
- Fixes emitting strings that having trailing or leading whitespace by wrapping them in CDATA blocks
- Adds expanded tests relying on whitespace invariance
- Adds utilities for describing deserialization, serialization, and round trip tests, including a failing example
=> Nail down whitespace nonsense in rbx_xml

README.md, rbx_xml/src/deserializer.rs, rbx_xml/src/serializer.rs, rbx_xml/src/types/mod.rs, rbx_xml/src/types/referent.rs
Closes #12.
This ended up being pretty hairy relative to introducing other property types.
Every time we encounter a Ref property, keep track of the instance's ID, the property name, and the referent the property is being set to. Because we can encounter instances in any order, we might not know what instance the referent points to yet, and rbx\_dom\_weak explicitly doesn't let you pick what IDs your instances get.
After we've deserialized all instances and their properties, we step through the table of 'ID rewrites', with one entry per non-null Ref property. We find the instance with the given ID (which should always exist) as well as which ID the referent value points to. If the referent points to an instance that ended up actually existing, we insert our freshly minted Ref property.
=> Refs in rbx_xml

.travis.yml, README.md, rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/brick_color.rs, rbx_dom_weak/src/lib.rs, rbx_dom_weak/src/value.rs
BrickColors are serialized as normal numbers, so this is the best way to do it I feel.
Makes use of TryFrom<T>, stabilized in Rust 1.34.0.
=> BrickColor support

rbx_dom_weak/src/value.rs, rbx_xml/src/deserializer.rs, rbx_xml/src/serializer.rs
Closes #36.
I think we can get away with removing `try_convert` and only supporting `try_convert_ref`. In the worst case, it incurs a copy conversion, which I think might be fine if we can make it only happen in the conversion case.
=> Stabilize RbxValue::try_convert_ref API

rbx_xml/src/types/numbers.rs, rbx_xml/test-files/inf-and-nan.rbxmx, rbx_xml/tests/round_trip.rs
=> Add support for INF and NAN

rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/tree.rs
This PR adds `RbxTree::move_instance`, which is a new-and-improved version of the old `transplant` method from pre-1.0 versions of rbx\_dom\_weak.
This paves the way to start adding more things onto `RbxTree`, like metadata and the shared string dictionary. We can then adjust the `rbx_xml` and `rbx_binary` APIs to instead return entire trees instead of decoding into trees in-place. This simplifies their APIs and makes everything easier to reason about, especially in failure cases!
=> Implement RbxTree::move_instance and shore up other DOM methods

generate_reflection/src/run_in_roblox.rs, rbx_xml/src/deserializer.rs, rbx_xml/src/error.rs, rbx_xml/src/lib.rs, rbx_xml/src/serializer.rs, rbx_xml/tests/deserializer_legacy.rs, rbx_xml/tests/errors.rs, rbx_xml/tests/fire.rs, rbx_xml/tests/referent.rs, rbx_xml/tests/round_trip.rs, rbx_xml/tests/value_conversion.rs
This PR rewrites the rbx_xml public API to be configurable and to improve its ergonomics.
The new base APIs are:
```rust
fn from_reader<R: Read>(
reader: R,
options: DecodeOptions,
) -> Result<RbxTree, DecodeError>;
fn to_writer<W: Write>(
writer: W,
tree: &RbxTree,
ids: &[RbxId],
options: EncodeOptions,
) -> Result<RbxTree, EncodeError>;
```
Parameters were shaved out of what was `rbx_xml::decode` since the reader now decode into a new tree and expects you to move it into an existing tree if you have one with `RbxTree::move_instance`. This may prove to be a little slower, but makes it easier to handle error scenarios and makes small examples simpler.
The encoder API still takes a lot of parameters. This is tricky to simplify because of the way places are serialized, since they ignore …
=> New rbx_xml API

rbx_xml/src/core.rs, rbx_xml/src/serializer.rs, rbx_xml/test-files/part.rbxmx, rbx_xml/tests/parts.rs
Fixes #55.
This PR fixes how rbx_xml's serializer converts types when serializing. Instead of trying to convert to the type given by the canonical property descriptor, we'll instead try to convert to the type given by the _serialized_ property descriptor. This is the one referred to by the `serialized_name` field of a property descriptor.
=> Fix type conversions in  rbx_xml serialization

rbx_xml/CHANGELOG.md, rbx_xml/src/deserializer.rs, rbx_xml/src/error.rs, rbx_xml/src/serializer.rs
Closes #57.
This PR changes rbx_xml to turn property type conversion failures (ie irreconcilable differences from the reflection database) into serialization/deserialization failures. This makes rbx_xml more strict and should help us catch problems quicker down the line.
=> Make failed type conversions in serialization cause errors

rbx_xml/src/deserializer.rs, rbx_xml/src/error.rs, rbx_xml/src/lib.rs, rbx_xml/src/serializer.rs, rbx_xml/tests/deserializer_options.rs, rbx_xml/tests/serializer_options.rs
This PR takes advantage of `DecodeOptions` and `EncodeOptions` to actually let the user set what kind of behaviors they want.
Options are:
- Ignore unrecognized properties (the default)
- Read/write unrecognized properties as-is (will probably be used by Rojo, at least in the short term)
- Error on unrecognized properties
- Completely turn off reflection and deserialize everything as-is
=> Add real configuration options to rbx_xml

rbx_xml/src/deserializer_core.rs, rbx_xml/src/serializer_core.rs, rbx_xml/src/types/colors.rs, rbx_xml/src/types/numbers.rs, rbx_xml/src/types/physical_properties.rs, rbx_xml/src/types/rect.rs, rbx_xml/src/types/udims.rs, rbx_xml/src/types/vectors.rs, rbx_xml/test-files/inf-and-nan.rbxmx
Closes #39 
I believe I got everything.
=> INF and NAN support everywhere

generate_reflection/src/run_in_roblox.rs, rbx_dom_lua/src/ReflectionDatabase/classes.lua, rbx_reflection/src/reflection_database/classes.rs
Closes #68.
Roblox recently started requiring that all built-in plugins have a signature associated with them that's verified by Studio.
This project doesn't have access to any signing tools to bypass that verification, so I'm downgrading the required permissions.
This has two effects:
1. Bad: the reflection database contains less information, since there is some serializable information that isn't available at core script security. `ParabolaAdornment` is probably a bad example since it's only meant for core scripts, but is something we lose information about with this change.
2. Good: the reflection database contains more accurate information for most consumers. Plugins like Rojo will no longer know about plugins that they couldn't read or write anyways.
=> Stop using built-in plugins for reflection generation

rbx_xml/src/deserializer.rs, rbx_xml/src/deserializer_core.rs, rbx_xml/src/types/binary_string.rs
Some XML model files from Roblox Studio have CRLF line endings. We fixed
handling these in BinaryString values, but didn't port the fix to work
with SharedString.
This change pulls that logic out into a new method and uses it for both
BinaryString and SharedString values.
=> Fix SharedString buffers with CRLF failing to decode

README.md, rbx_xml/CHANGELOG.md, rbx_xml/src/types/mod.rs, rbx_xml/src/types/ray.rs
Closes #87.
This enables rbx_xml to serialize `RayValue` instances and... nothing more. It's useful for conformance testing since we have _every_ instance.
=> Implement Ray type in rbx_xml

rbx_types/CHANGELOG.md, rbx_types/Cargo.toml, rbx_types/src/legacy_compat.rs, rbx_types/src/lib.rs
This will help smooth the transition to rbx_types/rbx_dom_weak 2.0 by implementing optional conversions between `Variant` and `RbxValue`.
=> Introduce legacy-compat feature for rbx_types

README.md, rbx_binary/src/core.rs, rbx_binary/src/deserializer.rs, rbx_binary/src/serializer.rs, rbx_binary/src/tests/models.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-intvalues__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-intvalues__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-intvalues__input.snap, rbx_binary/src/text_deserializer.rs
Wasn't sure where to put `read_interleaved_i64_array` or `write_interleaved_i64_array`, so I just added them after `read_referent_array` and `write_referents` since Int64 comes after Referent in terms of data types. Let me know if you think they should be near their i32 variants instead.
=> Implement Int64 type in rbx-binary

rbx_binary/src/core.rs, rbx_binary/src/deserializer.rs, rbx_binary/src/serializer.rs
Nothing too crazy here - this commit converts several loops that were over ranges to loops over iterators, removes a couple unnecessary references, and changes an `unwrap_or`  to an `unwrap_or_else`. Clippy is happy 😃
=> rbx_binary Fix clippy warnings

rbx_binary/Cargo.toml, rbx_binary/src/chunk.rs, rbx_binary/src/core.rs, rbx_binary/src/deserializer.rs, rbx_binary/src/serializer.rs, rbx_binary/src/text_deserializer.rs
Removes byte_order as a dependency of rbx_binary.
Doesn't implement new methods for niche data types like f64 and u16; these aren't used in many places, so it seems unnecessary.
Instead, those functions are replaced with inlines such as:
```rust
{
let mut bytes = [0; 8];
chunk.read_exact(&mut bytes)?;
f64::from_le_bytes(bytes)
}
```
I also resisted the urge to clean up any of the other functions since I wanted this to be a pure commit, but expect something like that in the future. Notably, I would like to (eventually) figure out a way to swap the `read_interleaved_TYPE_array` functions to also using `to_le_bytes` and `from_le_bytes`.
=> Remove byte_order as a dependency of rbx_binary

rbx_binary/src/core.rs, rbx_binary/src/serializer.rs, rbx_binary/src/tests/serializer.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__serializer__logical_properties_basepart_size.snap
This is a pretty involved change; I hope I've added enough documentation inline in the code to help guide people through the new design decisions here.
This is a concept that has existed in rbx-dom informally for awhile now, but I think I've finally found a good name: logical properties.
A logical property describes an attribute of an instance, and may have multiple property names. We already have special terms to describe two kinds of property names: canonical names and serialized names. The idea is that all names for a logical property have storage that aliases. One of them must be canonical and zero or one of them must be marked for serialization.
Examples of groups of property names that describe logical properties:
* `BasePart.Size` (canonical), `BasePart.size` (serialized)
* …
=> Fix rbx_binary's relationship to canonical and logical properties

README.md, format/binary.md, rbx_binary/src/deserializer.rs, rbx_binary/src/serializer.rs, rbx_binary/src/tests/models.rs, rbx_binary/src/tests/serializer.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__serializer__color3_to_color3uint8.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__serializer__part_color.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-unique-parts__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-unique-parts__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-unique-parts__input.snap, rbx_binary/src/text_deserializer.rs
As part of this PR I have made `serializer.rs` [use canonical property names when fetching property values to write, rather than the serialized names](https://github.com/rojo-rbx/rbx-dom/blob/1b2cfa7efef6556504fc9a732f13cbcad3615523/rbx_binary/src/serializer.rs#L446). This became an issue because `deserializer.rs` uses canonical names as keys for property maps. This caused the serializer to erroneously write default prop values since `instance.properties.get("Color3uint8")` results in a `None`. I alternatively could have made `deserializer.rs` use `"Color3uint8"` as the key, but that seems smelly to me.
I have also updated the test files submodule.
=> rbx_binary implement Color3uint8

.github/workflows/ci.yml, .github/workflows/clippy.yml, generate_reflection/src/defaults_place.rs, rbx_binary/benches/deserializer.rs, rbx_binary/benches/serializer.rs, rbx_binary/src/deserializer.rs, rbx_binary/src/serializer.rs, rbx_binary/src/tests/serializer.rs, rbx_binary/src/text_deserializer.rs, rbx_dom_weak/src/viewer.rs, rbx_reflection/src/database.rs, rbx_types/src/binary_string.rs, rbx_types/src/content.rs, rbx_types/src/referent.rs, rbx_types/src/serde_util.rs, rbx_xml/src/deserializer.rs, rbx_xml/src/deserializer_core.rs, rbx_xml/src/serializer.rs, rbx_xml/src/types/axes.rs, rbx_xml/src/types/cframe.rs, rbx_xml/src/types/color_sequence.rs, rbx_xml/src/types/content.rs, rbx_xml/src/types/faces.rs, rbx_xml/src/types/number_range.rs, rbx_xml/src/types/number_sequence.rs, rbx_xml/src/types/numbers.rs, rbx_xml/src/types/referent.rs, rbx_xml/src/types/shared_string.rs
Closes #137.
This PR pins a version of Rust that we'll use for running Clippy, and then makes warnings fail the build. Previously, Clippy was running on the latest stable and would only error for lints that were deny-by-default. This was better than nothing, but obviously not the full purpose of Clippy.
I'm also fixing all of the Clippy issues in the codebase at the same time, since I sorta have to.
=> Welcome Clippy into the codebase propertly

README.md, format/binary.md, rbx_binary/src/deserializer.rs, rbx_binary/src/serializer.rs, rbx_binary/src/tests/models.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-brickcolorvalues__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-brickcolorvalues__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-brickcolorvalues__input.snap, rbx_binary/src/text_deserializer.rs
Nothing unusual in here. This implementation returns an Err (in deserializer) or panics (in text_deserializer) when it encounters any unknown BrickColor codes, which matches the behavior of other types when they encounter a bad piece of data.
=> Implement BrickColor in rbx_binary

rbx_binary/src/deserializer.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__default-inserted-modulescript__decoded.snap
This PR changes the strategy that rbx_binary's deserializer uses when constructing instances. Instead of pushing properties into its `Instance` type and constructing `InstanceBuilder` objects when actually populating the `WeakDom`, we now incrementally build `InstanceBuilder` objects. This has the advantage of assigning referents much earlier in the process, which makes implementing the `Ref` type much easier.
As part of this change, I moved the portion of the code where we special case the `Name` property. I think the new home is a better spot.
Incidentally, this change let us drop a lot of boilerplate around constructing `Variant` objects because the `InstanceBuilder` methods are generic. This might increase compile times a small amount, but it is an ergonomic win that we should keep …
=> Tidy up the rbx_binary deserializer

rbx_types/src/shared_string.rs, rbx_types/src/variant.rs
This PR removes the serde implementations from `SharedString` and replaces them with `#[serde(with)]` annotations on `Variant`. This is a little more accurate to the actual state of these types. The new implementation also gracefully returns an error instead of panicking with `unimplemented!()`.
=> Remove Serialize/Deserialize from SharedString

rbx_binary/src/serializer.rs
Solving an issue brought up in PR #142, this adds a reasonable default to EnumValue while serializing. Studio loads invalid EnumValues without complaint, and `u32::MAX` is well outside of the range that Studio will ever need.
=> Add reasonable default for EnumValue to rbx_binary serializer

README.md, format/binary.md, rbx_binary/src/core.rs, rbx_binary/src/deserializer.rs, rbx_binary/src/serializer.rs, rbx_binary/src/tests/models.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__two-terrainregions__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__two-terrainregions__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__two-terrainregions__input.snap, rbx_binary/src/text_deserializer.rs
Nothing clever here, just getting us up to 100% coverage.
I believe this technically closes #117 since the remaining types (Region3, Region3int16, and Vector2int16) don't exist as properties.
=> Implement Vector3int16 in rbx-binary

README.md, rbx_dom_lua/src/EncodedValue.lua, rbx_dom_lua/src/EncodedValue.spec.lua
This patch implements the remaining datatypes that are missing from rbx_dom_lua, and fixes problems with encoding the Rect type.
=> [rbx_dom_lua] Support Axes, Faces, and Ray, improve Rect support.

rbx_binary/src/deserializer.rs
This PR fixes two cases:
- PROP chunks with no data are now silently ignored in order to match Roblox behavior. This is important with the new partly-released `OptionalCoordinateFrame` type.
- Unknown value types are now ignored, but print one warning per unknown type ID. The warning contains the instance type and property name of the first property in the file that has this byte. I wanted to reduce the amount of warning spam that might happen when new files starting including a type.
We'll want to backport this to dom-v1 so that we're able to patch Rojo 6.x and potentially 0.5.x as well.
=> Make rbx_binary resilient to unknown value types

rbx_xml/CHANGELOG.md, rbx_xml/src/deserializer.rs, rbx_xml/src/error.rs, rbx_xml/src/types/mod.rs, rbx_xml/tests/snapshots/test_files__unknown_type.snap, rbx_xml/tests/test-files.rs
XML sibling to #168.
`read_xml_value` has changed to return a `Result<Option<Variant>, _>` instead of `Result<Variant, _>` to encode the possibility of an unknown value independently of deserialization errors. It's not excellent, but it's the best we can do with the way this codebase is structured right now.
=> Harden rbx_xml against unknown property types

README.md, format/binary.md, rbx_binary/src/cframe.rs, rbx_binary/src/deserializer.rs, rbx_binary/src/serializer.rs, rbx_binary/src/tests/models.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__optionalcoordinateframe-models__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__optionalcoordinateframe-models__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__optionalcoordinateframe-models__input.snap, rbx_binary/src/text_deserializer.rs, rbx_binary/src/types.rs, rbx_types/src/basic_types.rs, rbx_types/src/variant.rs
There's quite a bit of code duplicated between `CFrame` and `OptionalCFrame`. It's not clear to me how we can easily avoid it with the current structure of the code, especially in the deserializer.
`yaml-rust` serializes a `None` as a `~` in our snapshots. Do we want to change this, or is it okay?
=> Implement OptionalCoordinateFrame in rbx_binary

rbx_binary/CHANGELOG.md, rbx_binary/src/serializer.rs
The serializer does not handle the case where an instance ID refers to an unserialized instance, resulting in nothing being written. This PR ensures that the null `Ref` is written for all IDs that do not refer to an instance, whether their Refs are `None` or are simply invalid.
=> Fix null refs not being written for invalid instance IDs

docs/attributes.md
Stops the attributes doc page from looking like this:
=> Correct mistake in ColorSequence attribute documentation

docs/binary.md
Instead of treating the Color field of ColorSequenceKeypoint as an exception, CSK is specified as having fields for each color component. This is similar to how Ray is specified as six floats instead of two Vector3s.
=> Specify CSK value as color components

rbx_binary/src/serializer/state.rs, rbx_types/CHANGELOG.md, rbx_types/src/basic_types.rs, rbx_xml/CHANGELOG.md, rbx_xml/src/conversion.rs
`BasePart.Color` was being incorrectly serialized as a `Color3` instead of a `Color3uint8` in the XML format, as per rojo-rbx/rojo#443. This PR adds conversions between these two types mainly to address this issue, but also because they will likely be useful in the future.
=> Add conversions between Color3 and Color3uint8

rbx_dom_lua/src/EncodedValue.lua
rbx_dom_lua's `EncodedValue` types still had PascalCase fields from before #191. This change brings it into line.
=> Rename EncodedValue type fields from PascalCase -> camelCase

.github/workflows/ci.yml
Criterion recently [changed its MSRV to 1.46.0 and began using `matches!`](https://github.com/bheisler/criterion.rs/commit/976d51730ce479d3d032d2dbb176022e45b22b57),  causing our CI to fail.
=> Bump MSRV from 1.40.0 to 1.46.0

rbx_dom_lua/src/PropertyDescriptor.lua
For Rojo's two-way sync, the plugin needs to be able to get a property's data type from a `PropertyDescriptor` so that it can use `EncodedValue.encode` to encode values destined for the server. Rojo's reconciler used to have a method that was hard coded to do this only for the `String` type, but it was lost after https://github.com/rojo-rbx/rojo/commit/f66860bdfe1b6a5f0174465c0a6c964b56e304cb.
=> Add dataType member to rbx_dom_lua's PropertyDescriptor

.gitmodules, rbx_binary/src/serializer/state.rs, rbx_binary/src/tests/models.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__package-link__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__package-link__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__package-link__input.snap
When serializing a DOM containing a PackageLink to binary via remodel or rojo, it results in this error: `Unsupported property type: PackageLink.PackageId is of type Content`.
It appears the fix is to just add a fallback for the Content type.
=> Fix PackageLink binary serialization

rbx_binary/src/serializer/state.rs
This fix makes `collect_type_info` around 3.5x faster for the benchmark model submitted by @Brian1KB. Projects with more repeated instances will see bigger wins.
Before:
After:
=> Perf: Cache (name, value_ty) pairs before checking reflection

.github/workflows/ci.yml, .github/workflows/clippy.yml, README.md, rbx_binary/src/deserializer/state.rs
This fix should enable us to deserialize model files serialized between 2021-09-07 and 2021-10-12 that have the old version of the MaterialVariant property. We need to have a follow-up fix that'll make sure we don't have a regression when we update our reflection database patches later.
=> Implement a fix to try to catch MaterialVariant type mismatches

rbx_dom_lua/src/PropertyDescriptor.lua
property Descriptor would error here `customProperties[self.className][self.name]` since is some ceases `customProperties[self.className]` returns nil what would cause the script to error out.
=> fixed Property Descriptor Custom erroring

generate_reflection/src/plugin_injector.rs
I accidentally closed the last pull request by forgetting to commit again
https://github.com/rojo-rbx/rbx-dom/pull/239
=> safeguard for Plugins folder not existing inside the studio directory during reflection generation

docs/binary.md
Not sure how this happened or why it was never addressed, but it was brought to my attention and we should fix it.
=> Correct signature in binary spec file

docs/binary.md
I am genuinely unsure how this ended up being wrong, but I've discovered that we incorrectly list Float as being little-endian.
Floats are in fact big-endian. A simple look at rbx_binary's source will confirm that. This PR fixes it in the spec document.
=> Correct endian-ness for Float in binary spec file

rbx_binary/CHANGELOG.md, rbx_binary/src/serializer/state.rs, rbx_binary/src/tests/models.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__sharedstring__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__sharedstring__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__sharedstring__input.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__unions__encoded.snap, rbx_xml/tests/snapshots/test_files__sharedstring.snap, rbx_xml/tests/test-files.rs
Currently, the SSTR chunk is non-deterministic, where the ordering of the SharedStrings inside the array can change on each run.
We make this deterministic by sorting the shared strings array (based on its hash), and then assigning IDs afterwards.
Dependent on the test files introduced in https://github.com/rojo-rbx/rbx-test-files/pull/16
=> Make SSTR chunk deterministic

README.md, docs/binary.md
Roblox added support for ZSTD compression alongside existing LZ4 compression. It's not very intuitive, but I've documented it here. I can provide a link to what I mean when I say `ZSTD frame` if it's deemed necessary but it should be obvious to anybody who's implementing ZSTD compression since it's normal vocabulary for that algorithm.
This also corrects some laziness and documents the `Bytecode` data type! We haven't documented it because it's not very useful to 3rd party users but I figure we should get to it eventually. I'm optimistically assuming we won't ever support it in `rbx_dom_lua` because why would we do that, but I guess I'm open to changing it.
The documentation comes with a warning against running unsigned bytecode. In a perfect world, this would be unnecessary. …
=> Document ZSTD compression and Bytecode data type in binary spec file

rbx_xml/Cargo.toml, rbx_xml/src/types/font.rs, rbx_xml/tests/snapshots/test_files__empty_font.snap, rbx_xml/tests/snapshots/test_files__font.snap, rbx_xml/tests/test-files.rs
In the past, Roblox serialized `Font` properties as empty tags. Although they've stopped doing that, there are still models in the wild with that format for tags. This adds support for empty Font tags by just returning the default value for `Font` when the tag is empty.
Relies on https://github.com/rojo-rbx/rbx-test-files/pull/19.
=> Fix support for empty Font tags in rbx_xml

docs/index.md, docs/xml.md
Wrote out a spec file for the XML file format since it's long overdue. I would love feedback on this because I'm not 100% convinced on some of the descriptions, but it should hopefully be workable.
Rendered document is [here](https://github.com/Dekkonot/rbx-dom/blob/xml-spec/docs/xml.md).
---
I'd also like feedback on whether or not we should document `Qdir`/`QFont` since they're not really useful to anybody but Roblox. I can definitely see the usefulness of having that information if you were working with settings files, but that seems like an uncommon use case.
The same question applies to more esoteric elements like `MetaBreakpoints` and `ScriptDocs`. I'm leaning towards no, since those are really obscure and are only seen in internal files that aren't used for models or places, but …
=> Fill out XML spec document

docs/assets/css/style.scss
At the moment, block quotes are quite frankly unreasonably large on the doc site. This patches the CSS for it to make their text equivalent to an H3 instead of being larger than H2.
For reference, this is how it looks right now:
And this is how it looks after the change:
=> Make Blockquotes more reasonably sized in doc site

.github/workflows/ci.yml, .github/workflows/clippy.yml, README.md, generate_reflection/src/main.rs, rbx_types/src/attributes/writer.rs, rbx_types/src/font.rs, rbx_xml/src/deserializer_core.rs, rbx_xml/src/types/tags.rs
We don't actually get any benefit from pinning our CI version beyond knowing our MSRV. This is because we aren't keeping lock files in the repository and we've historically just bumped the pinned version until it works.
To prevent this from ever becoming a problem again, we should simply not pin our versions. This has a consequences for Clippy because it means that our CI may suddenly fail in the future, but honestly Clippy lints should be fixed anyway so I don't think that's a bad thing.
=> Remove pinned version from workflows

CODEOWNERS
Given LPG's decision to exit the Roblox ecosystem, it makes very little sense for him to be requested as a reviewer for every PR that opens in this repository. I'm acting as the maintainer so it makes sense for me to at least be requested on every PR.
I could merge this without any comment but I feel like getting explicit approval would be good.
=> Remove LPGhatguy as codeowner, add Dekkonot as main codeowner

rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/dom.rs
Downstream in https://github.com/filiptibell/lune/issues/48, a potential stack overflow was discovered with the implementation of `WeakDom::insert`. This was because we recursively traverse the tree of any `InstanceBuilder` inserted into a Dom.
This PR swaps us over to use a queue instead of recursion, which resolves the stack overflow. it results in slightly more memory use overall (we're allocating a queue now, so there is a memory overhead) but it shouldn't be noticeable for normal uses.
=> Fix potential stack overflow with WeakDom::insert

.gitignore, aftman.toml, foreman.toml
A quick PR to migrate from foreman to aftman and upgrade the tools. I also removed the `/roblox.toml` from the `.gitignore` since selene doesn't generate it in the project directory anymore.
=> Migrate to aftman

rbx_binary/src/core.rs, rbx_binary/src/tests/core_read_write.rs, rbx_binary/src/tests/mod.rs
write_interleaved_bytes fails right now because it's just writing the bytes in their original sequence (see the results [here](https://github.com/rojo-rbx/rbx-dom/actions/runs/5296791237/jobs/9588138111))! This PR aims to close #286 by tweaking write_interleaved_bytes' implementation to interleave the bytes as it should.
=> Fix write_interleaved_bytes so that it actually writes interleaved

rbx_dom_weak/src/dom.rs, rbx_types/src/unique_id.rs
Closes #285, using Approach 1 as described in the issue. I ended up having to touch `WeakDom::transfer` as well, because that method could also create collisions.
It feels a bit icky to hard code the property name in these checks, but it's *very* unlikely that we or Roblox will ever want to give it a different name.
This PR additionally changes `WeakDom::insert` to accept a none `Ref` for the parent (previously, it'd just fall over and panic). The reason why is that I wanted to reuse the `UniqueId` checking code in `WeakDom::new` (to uphold the invariant even when the prop is in the root builder), but `WeakDom::insert` did not allow a none parent. The only difference for insertions with none parent vs some parent is whether the parent's list of children is extended, so it's pretty minimal …
=> Prevent UniqueId collisions within WeakDom's API

README.md
Fixes an itty-bitty mistake we didn't notice during the `UniqueId` addition
=> Fix formatting of property name in `UniqueId` coverage table entry

rbx_binary/src/deserializer/error.rs, rbx_binary/src/deserializer/state.rs
Closes #292.
Not really sure about `PropertyError` for the error variant name, maybe there is a better way to phrase it?
=> Fail on invalid attributes in rbx_binary deserializer

docs/binary.md
The docs for the binary format's `CFrame` representation are a bit wrong: the rotation matrix is actually stored in row-major order, and not column-major order as the current docs suggest. This can be verified by reviewing the implementation (which reads the rotation matrix in row-major order), changing rotation matrices in Roblox Studio and inspecting the output, and reviewing other community specifications such as the [RobloxFileSpec](https://www.classy-studios.com/Downloads/RobloxFileSpec.pdf).
=> Correct binary CFrame docs to say the matrix is in row-major order

rbx_binary/src/tests/models.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__folder-with-font-attribute__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__folder-with-font-attribute__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__folder-with-font-attribute__input.snap, rbx_types/CHANGELOG.md, rbx_types/src/attributes/error.rs, rbx_types/src/attributes/reader.rs, rbx_types/src/attributes/type_id.rs, rbx_types/src/attributes/writer.rs, rbx_xml/src/tests/models.rs, rbx_xml/src/tests/snapshots/rbx_xml__tests__folder-with-font-attribute__decoded.snap, rbx_xml/src/tests/snapshots/rbx_xml__tests__folder-with-font-attribute__roundtrip.snap
Closes #290.
Should the folder-with-font-attribute test files have more & varied font attributes added? I sort of want to add more, but I think the spec is correct, and I'm not sure how important it is to test against more values here
=> Implement font attributes

docs/compatibility.md
Turns out I was just outright wrong about BrickColor properties and for some reason didn't think to check (in my defense, I checked the other things I listed, I just forgot BrickColor for some reason).
Also, I forgot that serializing string properties might break under a specific scenario. Not something I plan to fix, but worth noting.
=> In compatibility doc, fix BrickColor concern and add section on strings with ]]>

rbx_binary/src/deserializer/state.rs
This PR supports widening ints & floats from 32 bits to 64 bits.
Basically, if we deserialize a property we expect to be 64 bits and it's actually 32 bits, we can safely convert over.
This fixes issues where Roblox previously had values serialized as 32 bits, but then they got upgraded to 64 bits later on. This only really occurs in older files, but it's a good blanket fix to have regardless.
There might be a better solution with migrations but I'm not as familiar with that; we can always remove this change if that gets figured out. I don't think this will break anything, unless Roblox goes from 64 back to 32 for a value and rbx_dom doesn't update in time, though that doesn't seem very likely. It's more likely that this will automatically migrate a value if Roblox changes something from …
=> Add int/float widening from 32 to 64 bits for rbx_binary

docs/patching-database.md
Was looking through the migration docs and notices this minor issue.
The `Roblox added a new property, but modifying it from Lua requires a special API` section was duplicated, seemingly split into 2 parts.
This change simply puts it together into one part.
=> Fix duplicate section in patching docs

rbx_xml/src/conversion.rs, rbx_xml/src/deserializer.rs, rbx_xml/src/tests/basic.rs
With issue #301, it's became clear we need a way to widen integers and floats from 32-bit to 64-bit since older models may have outdated types for number properties. This PR implements widening for `Int32` and `Float32`, giving them a very simple conversion to `Int64` and `Float64` respectively. This should solve the linked issue in the XML format and prevent it from being a problem for floats as well.
Support in `rbx_binary` is straightforward but the author of that issue has a fix ready to merge, so I'll let them do it. :smile:
=> Add int/float widening support to rbx_xml

rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/dom.rs, rbx_dom_weak/src/snapshots/rbx_dom_weak__dom__test__clone_into_external-2.snap, rbx_dom_weak/src/snapshots/rbx_dom_weak__dom__test__clone_into_external.snap, rbx_dom_weak/src/snapshots/rbx_dom_weak__dom__test__clone_within.snap
Closes #282 by implementing `WeakDom::clone_within` and `WeakDom::clone_into_external`.
=> Implement instance cloning methods in WeakDom

gen-reflection.bat
Though it is heresy to admit it, I do run windows on my machine and have been manually typing out the command to generate the reflection database. I think it'd be cool if I didn't have to do that anymore.
It's functionally identical to the bash script, just for batch.
=> Add gen-reflection equivalent for windows

patches/sound.yml
closes #320 and https://github.com/rojo-rbx/rojo/issues/742
- `RollOffMinDistance` serialize as `EmitterSize`
- `RollOffMaxDistance` serialize as `xmlRead_MaxDistance_3`
=> RollOff Patch

rbx_binary/src/serializer/state.rs, rbx_xml/src/core.rs
Closes #329.
This PR prevents rbx_xml and rbx_binary from serializing migrated properties. As stated in the linked issue, it's only possible for migrated properties to end up in the dom by specifically inserting them, but I think it's best to avoid any inconsistencies here.
=> Don't serialize migrated properties

rbx_binary/README.md, rbx_types/README.md, rbx_xml/README.md
`rbx_types`, `rbx_binary`, and `rbx_xml` all have outdated information in their README so I think we should fix that.
=> Update READMEs of crates to remove outdated info

.gitignore
I'm getting tired of having to ignore these and they're common in the Roblox development environment.
=> Make gitignore ignore .vscode and sourcemap.json

docs/binary-strings.md, docs/index.md
`MaterialColors` and `Tag` aren't documented right now. This documents them and also moves `BinaryStrings` their doc page. As a byproduct, I've moved attributes to there too.
I'm not 100% on the formatting I've used for the binary strings spec but hopefully it's good enough.
=> Give BinaryStrings their own documentation

rbx_binary/src/serializer/state.rs, rbx_types/src/unique_id.rs
Fully resolves #324 by making `UniqueId`'s default a null value, which may appears many times in a file.
Due to #327, it shouldn't affect anyone, but it's more 'correct' behavior anyway, so it's what we should be doing.
Tested in a version where `UniqueId` serializes using the following code:
```rs
use std::fs::File;
use rbx_dom_weak::{types::UniqueId, InstanceBuilder, WeakDom};
fn main() {
let dom = WeakDom::new(
InstanceBuilder::new("Workspace").with_children([
InstanceBuilder::new("Folder")
.with_property("UniqueId", UniqueId::now().unwrap())
.with_name("UniqueId set"),
InstanceBuilder::new("Folder"),
InstanceBuilder::new("Folder"),
InstanceBuilder::new("Folder"),
]),
);
rbx_binary::to_writer(File::create("out.rbxl").unwrap(), &dom, &[dom.root_ref()]).unwrap()
}
```
=> Make `rbx_binary` use nil UniqueId for default value

rbx_xml/src/core.rs, rbx_xml/src/serializer.rs, rbx_xml/src/tests/basic.rs, rbx_xml/src/tests/snapshots/rbx_xml__tests__basic__bad_migrated_property.snap, rbx_xml/src/tests/snapshots/rbx_xml__tests__basic__migrated_properties.snap
A companion to #339 and related to #335 as well.
As hoped for in 339, this was in fact much easier. We already have a mechanism for replacing names and values during serialization in rbx_xml, so it wasn't hard to add migrations to that process.
Unlike in the rbx_binary implementation, there's no compatibility concern if a migration fails. I've noted that in the source, but for posterity, if one fails and we allow a property to not be migrated, it'll still load just fine in Studio so there's not any real concern.
=> Perform property migrations in rbx_xml serializer

rbx_binary/src/serializer/state.rs, rbx_binary/src/tests/serializer.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__serializer__migrated_properties.snap
Related: #335 
Yeah, so this sucked pretty hard. rbx_xml will be easier (I hope)...
I've added descriptions to some of the commits here in an attempt to elucidate my thought process, if anything is unclear please ask questions
=> Perform property migrations in rbx_binary serializer

rbx_binary/src/core.rs
This migrates the various `read_interleaved_XXX_array` and `write_interleaved_XXX_array` functions to use `read_interleaved_bytes` and `write_interleaved_bytes` respectively.
The end result is a lot simpler code and has no cost associated with it (I checked the assembly, both versions give us basically the same instructions). Benchmarking also supports this, as the compilation time on my machine is basically the same before and after once you account for noise.
Also I added documentation to all these functions and the integer transforming functions because I didn't like them sitting there undocumented.
=> Use generic interleaving methods for `rbx_binary` core

rbx_binary/CHANGELOG.md, rbx_binary/Cargo.toml, rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/Cargo.toml, rbx_reflection/CHANGELOG.md, rbx_reflection/Cargo.toml, rbx_reflection_database/CHANGELOG.md, rbx_reflection_database/Cargo.toml, rbx_types/CHANGELOG.md, rbx_types/Cargo.toml, rbx_xml/CHANGELOG.md, rbx_xml/Cargo.toml
Since this is the first release I am performing for rbx_dom, I would appreciate a once over to make sure I didn't make any mistakes with versions!
I will merge this PR with a rebase, so no worries about losing commits here.
=> Prep crates for new release

rbx_dom_lua/src/EncodedValue.lua
Right now, rbx_dom_lua's round trip test fails on MaterialColors:
```
ken@DESKTOP-NIUUROA:~/projects/rbx-dom/rbx_dom_lua$ ./test
Building project 'rbx_dom_lua test place'
Built project to TestPlace.rbxlx
Test results:
[-] RbxDom
[-] EncodedValue
[-] round trip MaterialColors
0 passed, 1 failed, 34 skipped
1 test nodes reported failures.
Errors reported by tests:
TestService: ReplicatedStorage.RbxDom.EncodedValue.spec:63: Round-trip results did not match.
Expected:
{"MaterialColors":{"Grass":[106,127,63],"Rock":[102,108,111],"Basalt":[30,30,37],"Sand":[143,126,95],"Sandstone":[137,90,71],"Brick":[138,86,62],"Cobblestone":[132,123,90],"Glacier":[101,176,234],"Ground":[102,92,59],"Snow":[195,199,218],"WoodPlanks":[139,109,79],"Limestone":[206,173,148],"Slate":[63,127,107],"Salt":[198,189,181] …
```
=> Return pod in MaterialColors Lua encoder

rbx_types/src/shared_string.rs
In theory, this should fix the race condition. 
Fixes #350
=> Correct race condition in SharedString Drop impl

rbx_types/CHANGELOG.md, rbx_types/src/material_colors.rs
Closes #353.
This also modifies `MaterialColorsError` to be a generalized error for both `MaterialColors` and `TerrainColors`. This is technically a breaking change because the enum is publicly exposed, but I don't think it will seriously impact anyone beyond adding a new variant to the enum.
=> Implement FromStr for TerrainMaterials

rbx_types/CHANGELOG.md, rbx_types/src/error.rs, rbx_types/src/material_colors.rs, rbx_types/src/unique_id.rs, rbx_xml/src/error.rs, rbx_xml/src/types/unique_id.rs
At the moment, the error types for `UniqueId` and `MaterialColors` are exposed. This means that every change to their structure is breaking, including adding variants.
We should use the `Error` type defined by `rbx_types` instead. This PR changes it to do that. Additionally, it cleans up an implementation in `rbx_xml` that relied upon this type being exposed but that's not user facing so it is not noted in the changelog.
=> Dont expose `MaterialColorsError` and `UniqueIdError`

Cargo.toml, rbx_dom_weak/src/instance.rs
This PR Fixes a couple clippy lints that recently cropped up - we were calling `into_iter` unnecessarily in some `InstanceBuilder` methods
I also noticed a warning about the Rust 2021 feature resolver, so I set `workspace.resolver = "2"` to silence it. It looks to work just fine and I can't see any significant drawbacks - see https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html for details
=> Fix useless conversion lints, use Rust 2021 feature resolver

README.md, rbx_binary/CHANGELOG.md, rbx_binary/src/deserializer/state.rs, rbx_binary/src/serializer/state.rs, rbx_binary/src/tests/models.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__number-values-with-security-capabilities__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__number-values-with-security-capabilities__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__number-values-with-security-capabilities__input.snap, rbx_binary/src/text_deserializer.rs, rbx_binary/src/types.rs
This PR implements `SecurityCapabilities` parsing in rbx_binary. I chose to use `read_interleaved_i64_array` and `write_interleaved_i64_array` because Roblox appears to serialize it this way, and it's straightforward enough to cast between `u64` and `i64`.
=> Implement SecurityCapabilities in rbx_binary

rbx_dom_lua/src/EncodedValue.lua, rbx_reflector/src/cli/values.rs
With the introduction of SecurityCapabilities in #359, a value was added to the roundtrip test for rbx_dom_lua. This caused tests to begin to fail, as no pod was ever provided. However, in keeping with the theme of "we don't provide pods for values we don't use", we should simply not include a value for this type in tests to begin with.
This PR does exactly that, and allows rbx_dom_lua tests to pass once more.
=> Don't include SecurityCapabilities test in rbx_dom_lua

rbx_binary/CHANGELOG.md, rbx_binary/src/serializer/state.rs, rbx_binary/src/tests/serializer.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__serializer__default_shared_string.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__unions__encoded.snap, rbx_types/CHANGELOG.md, rbx_types/src/shared_string.rs
At the moment, when we generate a default for SharedString in rbx_binary, we neglect to add it to the pool of strings that are serialized into an SSTR chunk. This is a problem in of itself, but it also causes our PROP serialization to panic because it directly indexes into a hashmap, assuming this can't happen.
This PR fixes both. We now add the default SharedString to the pool when we generate it, and also emit a proper panic message when a value is not present in the case a bug of this sort crops up again.
Also, I changed a debug log that was spamming the output during serialization because it logged the debug of the entire `TypeInfos` structure. `SharedStringHash` now implements `Display` as well.
=> Fix potential crash in rbx_binary when serializing default SharedString

rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/dom.rs, rbx_dom_weak/src/snapshots/rbx_dom_weak__dom__test__clone_multiple_into_external.snap
Related: filiptibell/lune#110
It is not possible to preserve refs that point across subtrees using `WeakDom::clone_into_external` because a new `CloneContext` is used for each invocation - this new method gives a way to use one `CloneContext` for multiple subtrees!
Not sure about the method name, docs could probably be a little better, etc.
=> Implement method for cloning multiple instances into external dom

docs/binary.md
It turns out that the Roblox documentation was totally wrong and I was misled into writing that `CFrame` stores the `XVector`, `YVector`, and `ZVector` (these properties are NOT the rows of the matrix - [Roblox docs have recently been updated to reflect this](https://create.roblox.com/docs/en-us/reference/engine/datatypes/CFrame)). This PR simply writes the components of the rotation matrix in row-major order in our docs for binary `CFrame`.
=> Fix saying CFrame components are XVector, YVector, and ZVector

README.md
Ignore the fact I accidentally pushed this branch to upstream instead of origin. :-)
Since making a release is kind of a nightmare right now, it's probably worth writing down what order packages have to be updated in. Long-term we should try to automate this but until then, a stopgap is to put instructions in the README (or somewhere else, I guess).
=> Add basic instructions for cutting a new release

rbx_binary/CHANGELOG.md, rbx_binary/src/serializer/state.rs
In #361, we forgot to add the fallback default for `SecurityCapabilities`. This means when some instances are missing `Instance.Capabilities` (these are instances that were saved before `SecurityCapabilities` existed), and other instances *do* have this property, the binary serializer errors out. This PR adds the fallback default so this doesn't happen.
=> Add fallback default for SecurityCapabilities

rbx_dom_lua/src/EncodedValue.lua
It looks like this coder/decoder was introduced in imitation of some other types, but the other types that have erroring implementations either:
* Do not exist on any instance (`Region3`)
* Are special-cased elsewhere downstream (`Ref`)
* Wouldn't work anyway? (`SharedString`, although I think there is a case to be made that `SharedString` should NOT have an erroring lua coder/decoder)
`SecurityCapabilities` exists on *all* instances so an erroring implementation is inappropriate and causes problems for Rojo as per rojo-rbx/rojo#802. I think we can just remove the lua encoder/decoder, like how `UniqueId` simply doesn't have them either.
=> Remove erroring SecurityCapabilities lua coder/decoder

rbx_types/src/attributes/writer.rs
This was my fault (I didn't finish the job in PR #370).
=> Fix clippy lint in rbx_types

rbx_dom_lua/src/customProperties.lua
`Instance:SetAttribute` errors when passed invalid attribute names. The name must:
* be less than or equal to 100 characters;
* only contain alphanumeric characters, [and in the near future](https://create.roblox.com/docs/en-us/release-notes/release-notes-592), periods, hyphens, underscores, or forward slashes;
* must not use the RBX prefix, which is reserved by Roblox.
This PR adds validation to rbx_dom_lua's `Attributes` custom writer to guard against these, and if any fail, returns `false` (but will still attempt to set all the attributes). In the future, once Rojo's patch visualizer has more rich display of `Attributes` values, we could return a more detailed error with specific information about which ones failed.
The alternative is throwing the `SetAttribute` into a protected call, …
=> Add name validation to rbx_dom_lua Attributes writer

rbx_binary/CHANGELOG.md, rbx_binary/src/core.rs, rbx_binary/src/deserializer/mod.rs, rbx_binary/src/deserializer/state.rs, rbx_binary/src/serializer/mod.rs, rbx_binary/src/serializer/state.rs, rbx_xml/CHANGELOG.md, rbx_xml/src/core.rs, rbx_xml/src/deserializer.rs, rbx_xml/src/lib.rs, rbx_xml/src/serializer.rs
This allows the reflection database to be specified for serializing/deserializing in `rbx_binary` and `rbx_xml`. It does this by having the structs for these crates store a reflection database rather than using `rbx_reflection_database` inline. This doesn't change how the crates are used normally since they use the bundled database by default, but it provides the opportunity for tools like Rojo to specify their own database.
I took some liberties here also, and cleaned up the name of lifetimes a bit. Specifically, I've changed it so that all lifetimes that refer to a reflection database use a `'db` lifetime and all lifetimes that refer to a `WeakDom` use a `'dom` lifetime. This is to avoid confusion because `'a` is not specific or helpful.
=> Allow a database to be specified in both rbx_xml and rbx_binary

rbx_reflector/src/defaults.rs
Closes #345
Because of #375, it's possible to continue using `DecodePropertyBehavior::IgnoreUnknown` and simply swap to the in-progress database via `DecodeOptions::reflection_database`
=> Use in-progress db for rbx_reflector default place decode

rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/dom.rs
Title basically explains everything. Aside from the fact that it is good practise, `Default` is required e.g. when using `#[serde(skip)]` attribute.
=> Add `Default` implementation for `WeakDom`

rbx_reflector/src/cli/defaults_place.rs
On macOS, the file watcher emits a modify event after saving the defaults place in Roblox Studio, making it impossible to successfully use rbx_reflector. This PR fixes this by changing the event receive loop in rbx_reflector's defaults place command so that it also checks for modify events.
=> Break rbx_reflector file watcher receive loop after modify events

rbx_types/CHANGELOG.md, rbx_types/src/attributes/mod.rs
The original implementation of Attributes had an `iter` method but it did not implement `FromIterator` for `&Attributes`, making it so you couldn't use `for (key, value) in &attributes` and had to use `for (key, value) in attributes.iter()`. This changes that.
Additionally, `Extend` is a nice quality of life trait for containers so it's implemented here.
=> Implement IntoIterator for &Attributes and Extend for Attributes

docs/attributes.md
In pursuit of #383, this adds documentation of Enum-type attributes to the attribute spec document.
In the spec, I used `EnumItem` to be distinct from `Enum`, since both are important here. I don't think we should do it in the other documentation but I'm open to opinions.
Also, there were some backticks missing from the Font attribute documentation so I added them to make things consistent with the other entries.
=> Document Enum attributes in spec document

README.md, rbx_dom_lua/src/EncodedValue.lua, rbx_dom_lua/src/allValues.json, rbx_reflector/src/cli/values.rs
This PR closes #179 by adding an `OptionalCFrame` codec (and tests for it) to rbx_dom_lua.
As mentioned in #391, there was also a change needed to `EncodedValue.decode` so it doesn't error out when the encoded value pair is empty, which occurs when optional types (like `OptionalCFrame`) are unoccupied.
=> Add rbx_dom_lua OptionalCFrame codec

rbx_dom_lua/src/customProperties.lua
There was a mistake in #393 caused by some confusion around when `Model.WorldPivotData` is occupied and how it interacts `Model.PrimaryPart`. This PR removes a conditional that could cause incorrect behavior.
=> Remove PrimaryPart conditional in WorldPivotData custom setter

.gitignore, rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/instance.rs
This PR adds `with_referent` method for `InstanceBuilder` that allows to specify instance `Ref` manually. I also updated `.gitignore` for macOS users.
=> Add `InstanceBuilder::with_referent` constructing method

rbx_reflector/src/cli/defaults_place.rs, rbx_reflector/src/cli/generate.rs
This PR makes writing of database from `generate` subcommand in pretty-printed JSON optional by adding `--pretty` option. I think that it makes sense as these files are not intended to be read by humans and it reduces the file size from `1.6MB` to `796KB`.
=> Make pretty JSON optional for `generate` subcommand (`rbx_reflector`)

rbx_reflection/CHANGELOG.md, rbx_reflection/src/database.rs
It's fairly common to need a list of superclasses for a class, so we should provide a method for it. This is an implementation.
It uses a `HashSet` for convenience. It's slightly more expensive than a `Vec` but provides an easy mechanism for checking if a class is in the returned set, so it feels worth it.
=> Add method for getting the superclasses of an Instance to rbx_reflection

rbx_reflection/src/class_tag.rs, rbx_reflection/src/property_tag.rs, rbx_reflector/src/cli/generate.rs
Today I noticed that `rbx_reflector generate` failed to output a database due to a new datatype: 
```
Running `target/debug/rbx_reflector generate rbx_reflection_database/database.msgpack rbx_dom_lua/src/database.json --patches patches`
[INFO  rbx_reflector::cli::defaults_place] Installing Studio plugin
[INFO  rbx_reflector::cli::defaults_place] Starting Roblox Studio...
[INFO  rbx_reflector::cli::defaults_place] Waiting for Roblox Studio to re-save place...
[INFO  rbx_reflector::cli::defaults_place] Uninstalling Studio plugin
Please save the opened place in Roblox Studio (ctrl+s).
[INFO  rbx_reflector::cli::defaults_place] Place saved, killing Studio...
Error: Unknown type Path2DControlPoint
```
This got me thinking about how rbx_reflector can more gracefully deal with unknown data …
=> Harden rbx_reflector against unknown data types

docs/attributes.md
In the documentation the type ID of ColorSequence is set to `0x17` instead of `0x19`, which is already taken by the NumberSequence type.
https://github.com/rojo-rbx/rbx-dom/blob/c8ec8a9ac79c957c1628f93888fc6c5b0af119c5/rbx_types/src/attributes/type_id.rs#L48
=> Correct Type ID of ColorSequence in the Attributes documentation

rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/dom.rs
Adds a method for getting the UniqueId for a given referent in a WeakDom.
Technically unnecessary but a convenience function is helpful and there's nothing stopping us from linking referents more directly to their UniqueId in the future, which this method would benefit from.
=> Add method for getting UniqueId for referent

.gitignore, rbx_reflector/plugin.lua, rbx_reflector/src/cli/defaults_place.rs, rbx_reflector/src/cli/dump.rs
This PR brings automatic place saving to macOS, so it now works exactly the same as on Windows. It also pipes the `stdout` and `stderr` streams to `null` to get rid of extreme verbosity on macOS.
https://github.com/rojo-rbx/rbx-dom/assets/78505208/c488f168-dea0-4a3f-8f26-b83c8b5b4a66
> _New automation with old verbose output_
=> Improve `rbx_reflector` Roblox Studio automation and logging on macOS

rbx_dom_lua/src/customProperties.lua
`GetPivot` / `PivotTo` don't always reflect the value of `WorldPivotData`, actual value of which is reflected through `WorldPivot` (as mentioned in the #179 )
This can be observed by running the following tests in Studio
```lua
local Model = Instance.new("Model")
local Part = Instance.new("Part")
Part.Parent = Model
Model.PrimaryPart = Part -- If PrimaryPart doesn't exist then WorldPivot == GetPivot (Pretty sure)
Model.Name = "WPDTest"
Model.Parent = workspace
Model.WorldPivot *= CFrame.new(2.1, 2.3, 2.5) -- Try swapping this with PivotTo
local WorldPivot, GetPivot = Model.WorldPivot, Model:GetPivot()
print(WorldPivot)
warn(GetPivot)
print(WorldPivot == GetPivot)
-- Save the file & see it's contents
```
=> Changed WorldPivotData getter/setter to WorldPivot

rbx_types/CHANGELOG.md, rbx_types/src/attributes/mod.rs
Took a liberty with how the `drain` implementation works but it's fine because `BTreeMap` doesn't have a `drain` method built into it.
=> Add `clear` and `drain` implementations to `Attributes`

rbx_types/CHANGELOG.md, rbx_types/src/shared_string.rs, rbx_types/src/variant.rs
Implements Serde for SharedString. The implementation is pulled from `BinaryString` to avoid us having to do anything fancy.
This will allow users to specify SharedString properties in Rojo, which is of some importance.
=> Implement Serde for SharedString

rbx_binary/src/serializer/state.rs, rbx_reflector/src/api_dump.rs, rbx_types/src/basic_types.rs, rbx_types/src/referent.rs, rbx_xml/src/types/numbers.rs
babe wake up, new clippy version just dropped, and with it new lints.
Mostly in this case it was that we were using outdated stuff. Some dead code in rbx_reflector but we're ignoring it since we need it for Serde (well, we don't, but it'd be weird to just ignore all unknown values in the API dump)
=> Fix clippy lints across all crates

rbx_util/CHANGELOG.md, rbx_util/Cargo.toml, rbx_util/README.md, rbx_util/src/main.rs, rbx_util/src/remove_prop.rs
When debugging an issue that cropped up on the Roblox devforums yesterday, I wanted an easy way to remove every instance of property from a file (specifically, `SurfaceAppearance.Color`). Given that there's no easy way to do this without converting a file to XML, removing the property, then converting it back, I think it'd be helpful to include in rbx-util in the future.
=> Add command for stripping a specific property from Instances to rbx-util

rbx_reflection/src/database.rs
As mentioned in #420, there's an inconsistency in the design of `superclasses` with how `find_default_property` is going to work. It makes sense to operate on `ClassDescriptors` in database methods, so this PR just swaps `ReflectionDatabase::superclasses` to use one instead of a class name.
=> Change `ReflectionDatabase::superclasses` to use `&ClassDescriptor` instead of `&str`

rbx_binary/CHANGELOG.md, rbx_binary/Cargo.toml, rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/Cargo.toml, rbx_reflection/CHANGELOG.md, rbx_reflection/Cargo.toml, rbx_reflection_database/CHANGELOG.md, rbx_reflection_database/Cargo.toml, rbx_types/CHANGELOG.md, rbx_types/Cargo.toml, rbx_xml/CHANGELOG.md, rbx_xml/Cargo.toml
babe wake up, new rbx-dom version just dropped
Special shoutout to rbx_xml. Nothing has changed, we just need to update dependencies so that rbx_dom_weak doesn't have multiple versions in crates that include both rbx_binary and rbx_xml
=> Make new slate of releases

rbx_binary/src/serializer/state.rs, rbx_types/src/attributes/writer.rs
This PR removes an unnecessary clone and reference when writing font values to binary files or attributes, fixing a clippy lint that recently started being reported
=> Use as_deref instead of clone when writing font cached face ID

rbx_binary/CHANGELOG.md, rbx_binary/Cargo.toml
After the bugfix for rbx-binary, we should probably make a new release. That's this.
=> Release rbx-binary v0.7.6

rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/dom.rs
Iterating through WeakDoms is a common enough code pattern that I feel it warrants its own function. This implements those functions.
=> Implement descendant iterators for WeakDom

rbx_dom_lua/src/customProperties.lua
When implementing #374, we forgot to also validate attribute names when removing attributes from the existing instance. In addition to adding that validation, this PR reworks attribute set validation so we consider reserved names separately from invalid ones - we probably don't want to indicate failure on reserved names, since reserved attribute names seem to be Roblox implementation details and won't impact the correctness of results.
=> Validate attribute removals, handle reserved failures separately from invalid ones

rbx_binary/CHANGELOG.md, rbx_binary/Cargo.toml, rbx_binary/src/chunk.rs, rbx_binary/src/lib.rs, rbx_binary/src/serializer/mod.rs, rbx_binary/src/serializer/state.rs
Like the PR says. This adds the ability to specify what type of compression to use for `rbx_binary::Serializer` as well as support for zstd.
=> Support setting compression type for rbx_binary and support zstd compression

rbx_reflector/plugin.lua
This PR changes the rbx-reflector Roblox Studio plugin so that it waits for `game.Name` to change before checking that the place it's running in is the defaults place.
This is necessary because (likely) after https://devforum.roblox.com/t/place-open-improvements-test/3086811, `game.Name` is only set to the value specified in the place file sometime after opening the place, meaning that the rbx-reflector plugin in its current state will never run.
Since it doesn't seem prudent to assume that `game.Name` will always have this behavior, there is a two second timeout.
=> Wait for game.Name to change before running rbx-reflector plugin

rbx_binary/CHANGELOG.md, rbx_binary/src/deserializer/state.rs
I am using `rbx_binary::from_reader(input)` to load files in my [rust program](https://git.itzana.me/StrafesNET/asset-tool), and some of the files make the function spit out the error "stream did not contain valid UTF-8".
I decided that I'm proficient enough at Rust to find out how to fix this pesky issue myself, and here's what I've come up with.  I found two places which would produce this error and have patched them using the `String::from_utf8_lossy` function.
Here is an image of an offending section of a `Script.Source` property after it was mercilessly butchered into valid UTF-8:
=> Fix "stream did not contain valid UTF-8" using String::from_utf8_lossy

rbx_reflection/CHANGELOG.md, rbx_reflection/src/database.rs, rbx_reflection_database/src/lib.rs
I thought it was weird that database.superclasses() returns a Vec<ClassDescriptor> rather than an iterator, perhaps it should be replaced or supplemented by something like this?
=> rbx_reflection: Superclass Iterator

rbx_reflector/src/cli/generate.rs, rbx_xml/CHANGELOG.md, rbx_xml/src/tests/snapshots/rbx_xml__tests__formatting__serialized.snap, rbx_xml/src/types/content.rs, rbx_xml/src/types/mod.rs
Recently (release 645), Roblox renamed their existing `Content` type to `ContentId`. This broke `rbx_reflector` and also means that `rbx_xml` is technically wrong.
Long-term, we should probably rename `Content` to `ContentId` in `rbx_types`. This is breaking though, so for now we can just change what tag is written in `rbx_xml`.
=> Support ContentId in rbx_reflector and rbx_xml

rbx_binary/CHANGELOG.md, rbx_binary/src/core.rs, rbx_binary/src/deserializer/state.rs, rbx_binary/src/serializer/state.rs, rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/Cargo.toml, rbx_dom_weak/src/dom.rs, rbx_dom_weak/src/instance.rs, rbx_dom_weak/src/lib.rs, rbx_dom_weak/src/viewer.rs, rbx_reflector/src/defaults.rs, rbx_util/src/remove_prop.rs, rbx_xml/CHANGELOG.md, rbx_xml/src/deserializer.rs, rbx_xml/src/lib.rs, rbx_xml/src/serializer.rs, rbx_xml/src/tests/basic.rs, rbx_xml/src/types/referent.rs, rbx_xml/src/types/shared_string.rs
This PR closes #112 and (partially?) #457 by adding [ustr](https://docs.rs/ustr/latest/ustr/) as a dependency, using interned strings for property and class names, and using `UstrMap` for property maps.
On my M1 MacBook, this improves rbx_binary's "Serialize 10,000 Parts" and "Deserialize 10,000 Parts" benchmarks by ~46% and ~49%, respectively, and reduces the number of heap allocations by ~84% (but I only profiled allocations when deserializing, maybe allocations during serialization is something a reviewer can check). 
This change is breaking because it changes many public method signatures on `InstanceBuilder`, and changes the type of `Instance.properties` (which is public) from `HashMap<String, Variant>` to `UstrMap<Variant>`. 
For convenience, I had rbx_dom_weak re-export some ustr …
=> Intern property and class names, use UstrMap for properties

rbx_dom_weak/src/dom.rs
This PR adds a fast path for leaf instances to `WeakDom::insert`. When an instance does not have any children, then we don't need to create a queue, avoiding a heap allocation, and can perform the insertion then exit the method immediately.
On my machine, this improves rbx_binary's "Deserialize 10,000 Parts" benchmark by ~4%, and reduces the number of heap allocations by ~7%. Note that the effectiveness of this optimization depends on how many leaf instances the requested insertion has, so this improvement is probably overstated on this benchmark, which contains vastly more leaf instances than internal instances.
=> Don't create queue in WeakDom::insert for leaf instances

rbx_binary/src/deserializer/state.rs, rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/instance.rs, rbx_xml/src/deserializer.rs
This PR adds a new method `InstanceBuilder::with_property_capacity` which can preallocates `InstanceBuilder.properties`, and makes the rbx_xml and rbx_binary deserializers use it. Since we know how many properties any given instance will (likely) contain via the reflection database, this allows us to avoid resizes during deserialization.
On my machine, this improves rbx_binary's "Deserialize 10,000 Parts" benchmark by ~17%, and reduces the number of heap allocations by ~32%.
The fact that we're using the database's default properties to determine the capacity is a little hairy - we've discussed normalizing default properties in the database in #418, so we should remain mindful of this optimization, lest we inadvertently regress performance.
=> Preallocate property tables during deserialization

rbx_binary/src/deserializer/state.rs, rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/dom.rs
This PR adds a new method `WeakDom::reserve` that can preallocate additional space for instances, and makes the binary deserializer use it before adding instances.
On my machine, this improves rbx_binary's "Deserialize 10,000 Parts" benchmark by ~4%, reduces the number of heap allocations by a negligible amount, but allocates ~2.4MB less memory. 
I'm not sure if this should also call `reserve` on `WeakDom.unique_ids`, because UniqueIds won't always be present in inputs, and it could take a possibly significant amount of space for no reason.
=> Reserve space for additional instances in binary deserializer

rbx_binary/src/serializer/state.rs
For better rbx_binary serialization performance, this PR changes the type of `TypeInfo.properties_visited` from `HashSet<(Ustr, VariantType)>` to `UstrSet`, and changes the type of `TypeInfo.aliases` from `BTreeSet<Ustr>` to `UstrSet`. These changes are sound because:
*  The second tuple field in `TypeInfo.properties_visited` entries is not used for anything outside of the collection, and it's impossible for an instance to contain two properties that have the same name, but different types.
* The order of `TypeInfo.aliases` is unimportant. 
On my machine, serialization benchmark results compared to latest master are as follows:
```
100 Folders/Serialize   time:   [20.219 µs 20.256 µs 20.298 µs]                                   
thrpt:  [37.165 MiB/s 37.242 MiB/s 37.309 MiB/s]
change: …
```
=> Use UstrSet for TypeInfo.properties_visited and TypeInfo.aliases

rbx_binary/src/deserializer/error.rs, rbx_binary/src/deserializer/state.rs, rbx_dom_lua/src/Error.lua, rbx_dom_lua/src/customProperties.lua, rbx_xml/src/conversion.rs, rbx_xml/src/deserializer.rs, rbx_xml/src/serializer.rs
In #293, we changed the rbx_binary deserializer to bail completely when it fails to read attributes. This turns out to be a pretty bad idea, because it means when Roblox changes the attributes format, any files containing the new version cannot be parsed at all. 
This PR allows MaterialColors and Attributes to be parsed as BinaryStrings when they cannot be parsed into their specialized types in both rbx_binary and rbx_xml, and changes the corresponding rbx_dom_lua custom property codecs to fail gracefully under these conditions. I'm thinking we might want to do this for Tags too, but I'm not sure... let me know what you think!
=> Don't bail for MaterialColors and Attributes parse failures

rbx_reflector/src/cli/generate.rs
Currently, `rbx_reflector generate` bails immediately upon encountering a unknown serialized data type. This lets us know when we might need to implement a new data type, but it's kind of annoying to know only that there's a least one property that has the data type, and for the command to fail completely instead of generating a database.
This PR makes `rbx_reflector generate` print a warning and continue when encountering unknown serialized data types, rather than bailing. This allows the operator to see all of the properties, instead of just one, and will also actually generate the database.
=> Don't bail on attempt to reflect unknown serialized data types

docs/attributes.md, rbx_binary/src/serializer/state.rs, rbx_binary/src/tests/models.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__folder-with-enum-attribute__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__folder-with-enum-attribute__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__folder-with-enum-attribute__input.snap, rbx_dom_lua/src/EncodedValue.lua, rbx_dom_lua/src/allValues.json, rbx_dom_lua/test, rbx_dom_weak/CHANGELOG.md, rbx_reflector/src/cli/values.rs, rbx_types/CHANGELOG.md, rbx_types/src/attributes/error.rs, rbx_types/src/attributes/reader.rs, rbx_types/src/attributes/type_id.rs, rbx_types/src/attributes/writer.rs, rbx_types/src/basic_types.rs, rbx_types/src/variant.rs, rbx_xml/src/conversion.rs, rbx_xml/src/tests/basic.rs, rbx_xml/src/tests/models.rs, rbx_xml/src/tests/snapshots/rbx_xml__tests__folder-with-enum-attribute__decoded.snap, rbx_xml/src/tests/snapshots/rbx_xml__tests__folder-with-enum-attribute__roundtrip.snap
This PR closes #383 by by adding a new tagged enum variant, `EnumItem`, that contains the name of the `EnumItem` as well as its value, and implementing the attributes reader/writer against the [specification at rojo.dom.space](https://dom.rojo.space/attributes.html#enumitem).
Additionally, it adds a codec to rbx_dom_lua to handle the new `EnumItem` variant.
It also updates some docs, since the link that's currently there doesn't work anymore.
I went back and forth on what the fields should be named in the serde representation, and settled on `type` and `value`. This more or less mirrors `EnumItem.EnumType` and `EnumItem.Value` on Roblox - but maybe `type` should be `enumType` instead?
=> Implement enum attributes

rbx_binary/benches/README.md, rbx_binary/benches/suite/main.rs, rbx_binary/benches/suite/util.rs
This PR adds a benchmark for Miner's Haven, a real-world Roblox game that is open sourced at https://github.com/berezaa/minershaven. It's representative of workloads rbx_binary will see most often.
It also adds a readme that documents how the benchmark suite works and how to use it.
=> Add rbx_binary Miner's Haven benchmark and readme

rbx_types/src/basic_types.rs
This PR fixes an issue introduced in #470 where a configuration attribute did not respect the rbx_types' `serde`features, causing compilation to fail when building the crate without the `serde` feature enabled.
=> Fix EnumItem not respecting serde feature in field rename

rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/dom.rs, rbx_dom_weak/src/lib.rs
We expose `AHashMap` via `WeakDom::into_raw` so we should probably re-export it same as `UstrMap`. If we do that it makes sense to also implement the helper trait for it.
Also, we should use the actual `AHashMap` type rather than the HashMap alias because it impacts how it's surfaced in the type signature. Better to show explicitly that we're using `AHashMap` for this than have it silently disappear because the type is `HashMap`.
This came up while I was porting Rojo to use the new changes for Uplift, so I may end up with more pull requests if other UX issues come up.
=> Re-export AHashMap and give it a trait extension

rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/dom.rs
When reading files, we produce `WeakDom`s with one root that has multiple children. This allows for e.g. model files to have multiple roots, despite our DOMs only support one.
However, if you want to get a DOM read from a file and have one of the children at the root (as in e.g. Rojo) you need to jump through some hoops. The current way to handle that is essentially:
- Make a new `WeakDom` with the right class at the root
- Transfer children of the Instance into the new DOM
- Transfer properties from the Instance to the new DOM's root
This is fine, except that it breaks Ref properties: since you can't overwrite the root of a DOM, you have to make a new DOM, which means that inserting the other Instances creates new referents for each of them. Solving this is non-trivial because it …
=> Add WeakDom::from_raw

rbx_reflector/src/cli/defaults_place.rs
In [657](https://robloxapi.github.io/ref/updates/2025.html#version-96b5c87ce0ce4dff) `UserGameSettings` can no longer be inside a DataModel - same fix as in #481.
=> Fix Roblox Studio crashing when using `rbx_reflector`

docs/binary.md, docs/xml.md
Partially resolves #480.
Based on discussions with Roblox and observing some files, here are some spec files for the `Content` type.
I'm not writing it down in the spec file because it's an implementation detail, but for the curious: `ExternalObjectRefs` is used to preserve references while copy-and-pasting. Because of 'Cut' and pasting between sessions though, the actual `Object` that's being referenced has to be serialized so that the property can be intact even if the `Object` no longer exists. If it's loaded and the external reference exists and is valid, it's used but otherwise the value in `ObjectRefs` is used.
=> Document `Content` type in spec files

rbx_reflector/src/api_dump.rs
~~Roblox has a new security type. Yay.~~
Evidently, Roblox has had a WritePlayer security type for a very long time and it's the _actual_ underlying write security for `Player.Name` and `Player.UserId`. It was exposed starting in release 664, but it's been there for ages. I have confirmed with Roblox.
This should be the last one we have to worry about, as subsequent changes will happen under Capabilities. There's apparently also an "Unknown" security but I would hope we will never run into that in public builds of Roblox!
=> Add support for WritePlayerSecurity in API dump

rbx_types/src/lister.rs
~This is _technically_ a breaking change (?), but I don't think anyone is using the `fmt::Debug` output for Axes and Faces (the only uses in the entire crate) programmatically in a way that would break if we changed this.~
Actually, apparently `Debug` is unstable [(at least for derived `Debug` and the standard library)](https://doc.rust-lang.org/std/fmt/trait.Debug.html#stability), so I guess it isn't even a breaking change.
=> Fix `Lister` utility in `rbx_types`

rbx_dom_lua/src/EncodedValue.lua
Earlier this week I encountered some rbxm files that appeared to have the values of some NumberSequenceKeypoints as NaN. This would cause the rojo sync to fail as that value was being serialized as nil. Adding a zero here allowed the sync to complete successfully.
=> Added NaN protections

rbx_types/CHANGELOG.md, rbx_types/src/content.rs
While implementing Content for Lune, I've noticed that an ergonomic feature is missing from `Content`. We should fix that.
=> Add `Content::into_value`

rbx_types/CHANGELOG.md, rbx_types/src/content.rs
This is convenient if you want to always assume the Content is a Uri or an Object.
=> Add `Content::as_object` and `Content::as_uri`

rbx_types/CHANGELOG.md, rbx_types/src/referent.rs
There is no way to have a Ref as a compile time constant like so:
```rust
pub(crate) const NIL_REF:Ref=Ref::from_value(u128::MAX);
```
The alternative is to litter the code with runtime construction using FromStr:
```rust
let nil_ref:Ref="ffffffffffffffffffffffffffffffff".parse().unwrap();
```
The intended use case for this is to implement runtime nil instances with a specific constant Ref that refers to the "root nil instance" within the dom. The implementation maps the None variant of `Option<Ref>` into `NIL_REF` when assigning parent:
```rust
pub struct Instance{
referent:Ref,
}
impl Instance{
pub const fn nil()->Self{
Self{
referent:NIL_REF
}
}
}
impl mlua::UserData for Instance{
fn add_fields<F:mlua::UserDataFields<Self>>(fields:&mut F){ …
```
=> Const Ref Constructor

rbx_dom_weak/CHANGELOG.md, rbx_dom_weak/src/dom.rs
The commit history also includes a version with a different type signature that does not panic.
=> Implement `WeakDom::ancestors_of`

LICENSE.txt, rbx_binary/Cargo.toml, rbx_dom_weak/Cargo.toml, rbx_reflection/Cargo.toml, rbx_reflection_database/Cargo.toml, rbx_types/Cargo.toml, rbx_util/Cargo.toml, rbx_xml/Cargo.toml
After a brief discussion with Lucien, rbx-dom will be relicensed to be owned by the Rojo Developers. It was before, and then Roblox owned the repo, and when it was given back to Lucien he put himself as the owner. I've chosen to not reflect the incredibly confusing timeline under the assumption that nobody will care, but I _can_ reflect it in the license if we want.
In the same email, he suggested adding the current maintainers as authors to the various `Cargo.toml`s and I think that's a good decision so this PR does that too. I'll be opening a similar one for Rojo soon(tm).
I can attach the email I received if we want to be legally airtight but I generally default to not attaching emails to things unless I have to.
=> Update authors fields for crates and relicense repository

patches/audio-player.yml, patches/backpack-item.yml, patches/click-detector.yml, patches/decal.yml, patches/mouse.yml, patches/sound.yml, patches/ui-drag-detector.yml, patches/user-input-service.yml
- Migrates `BackpackItem.TextureId` to `TextureContent`
- Migrates `ClickDetector.CursorIcon` to `CursorIconContent`
- Migrates `DragDetector.ActivatedCursorIcon` to `ActivatedCursorIconContent`
- Migrates `Decal.ColorMap` to `ColorMapContent` (just in case, as they don't serialize but Roblox could change that)
- Migrates `Mouse.Icon` to `IconContent`
- Migrates `UIDragDetector.ActivatedCursorIcon` to `ActivatedCursorIconContent`
- Migrates `UIDragDetector.CursorIcon` to `CursorIconContent`
- Migrates `UserInputService.MouseIcon` to `MouseIconContent`
=> Migrate Content properties added since v684

docs/binary.md, docs/xml.md, rbx_binary/CHANGELOG.md, rbx_binary/src/deserializer/error.rs, rbx_binary/src/deserializer/state.rs, rbx_binary/src/serializer/state.rs, rbx_binary/src/tests/models.rs, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__physical-properties-acoustics__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__physical-properties-acoustics__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__physical-properties-acoustics__input.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-unique-parts__decoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-unique-parts__encoded.snap, rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-unique-parts__input.snap, rbx_binary/src/text_deserializer.rs, rbx_dom_lua/src/EncodedValue.lua, rbx_dom_lua/src/allValues.json, rbx_reflector/src/cli/values.rs, rbx_types/CHANGELOG.md, rbx_types/src/physical_properties.rs, rbx_xml/CHANGELOG.md, rbx_xml/src/tests/formatting.rs, rbx_xml/src/tests/models.rs, rbx_xml/src/tests/snapshots/rbx_xml__tests__formatting__deserialized.snap, rbx_xml/src/tests/snapshots/rbx_xml__tests__formatting__serialized.snap, rbx_xml/src/tests/snapshots/rbx_xml__tests__physical-properties-acoustics__decoded.snap, rbx_xml/src/tests/snapshots/rbx_xml__tests__physical-properties-acoustics__roundtrip.snap, rbx_xml/src/tests/snapshots/rbx_xml__tests__three-unique-parts__decoded.snap, rbx_xml/src/tests/snapshots/rbx_xml__tests__three-unique-parts__roundtrip.snap, rbx_xml/src/types/physical_properties.rs
Roblox has added a new field to `CustomPhysicalProperties` called `AcousticAbsorption`. This PR adds support for that field in rbx_types, **which is breaking**.
It also implements support for reading and writing this new field to rbx_xml and rbx_binary. This is not breaking.
I have confirmed with two separate Roblox engineers working on the acoustics system that the default for `AcousticAbsorption` when reading an existing `CustomPhysicalProperties` is `1.0`, so it's what our implementation goes with rather than making the field optional.
=> Update implementation of `PhysicalProperties` to include new `AcousticAbsorption` field
