rojo-rbx/rbx-dom

- rbx_tree/src/value.rs
- rbx_xml/src/deserializer.rs
- rbx_xml/test-files/model-d.rbxmx
Expanding XML parsing a bit more, to do things and stuff!
- Color3/Color3uint8 support
- String and bool parsing
- Children parsing
> [WIP] Expanding XML parsing

- rbx_binary/FORMAT.md
I switched out the reference to Rbx2Source with Roblox-File-Format, added a section about referent arrays, and tweaked a few things.
> Switched reference, added info about referent arrays.

- README.md
- rbx_dom_weak/CHANGELOG.md
- rbx_dom_weak/src/lib.rs
- rbx_dom_weak/src/value.rs
These types were a little bit more complicated than I expected, so they also add new standalone exported types.
> Add Ray, Rect, ColorSequence, and NumberSequence types

- README.md
- rbx_xml/CHANGELOG.md
- rbx_xml/src/types/color_sequence.rs
- rbx_xml/src/types/mod.rs
- rbx_xml/src/types/number_range.rs
- rbx_xml/src/types/number_sequence.rs
- rbx_xml/src/types/rect.rs
- rbx_xml/test-files/effects.rbxmx
- rbx_xml/tests/round_trip.rs
> Implement More Types in rbx_xml

- rbx_dom_weak/src/brick_color.rs
Whoops. Also adds `BrickColor::from_name`.
> Serialize/Deserialize for BrickColor

- rbx_xml/CHANGELOG.md
- rbx_xml/src/serializer.rs
This makes rbx_xml much more deterministic and should have minimal performance impact.
> Make rbx_xml output sorted properties

- .github/workflows/ci.yml
Part of ongoing work to start stripping away Travis-CI in favor of GitHub Actions!
> Add a workflow for GitHub Actions

- rbx_binary/Cargo.toml
- rbx_binary/benches/deserializer.rs
- rbx_binary/benches/serializer.rs
- rbx_binary/src/core.rs
- rbx_binary/src/deserializer.rs
- rbx_binary/src/lib.rs
- rbx_binary/src/serializer.rs
- rbx_binary/src/tests/serializer.rs
- rbx_binary/src/tests/snapshots/util__default-inserted-folder__decoded.snap
- rbx_binary/src/tests/snapshots/util__default-inserted-modulescript__decoded.snap
- rbx_binary/src/tests/util.rs
- rbx_binary/src/types.rs
This follows in the footsteps of the port for rbx_xml and is mostly mechanical.
> Port rbx_binary to rbx_dom_weak 2.0

- rbx_binary/FORMAT.md
This makes the document much easier to read and easier to edit!
> Remove crazy HTML tables from FORMAT.md

- rbx_binary/FORMAT.md
Also updates the description for the string type.
I'm not 100% on the integer transformation section so let me know if there are any issues with it or improvements you want to make.
> Add descriptions for several data types + accompanying storage notes

- README.md
- rbx_binary/src/deserializer.rs
- rbx_binary/src/serializer.rs
- rbx_binary/src/tests/models.rs
- rbx_binary/src/tests/serializer.rs
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__funny-uipadding__decoded.snap
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__funny-uipadding__encoded.snap
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__funny-uipadding__input.snap
- rbx_binary/src/text_deserializer.rs
Note https://github.com/Roblox/rbx-dom/commit/89a31273fcb81fef2e9097481eae160b884525be - is this ok?
> Implement UDim and update test-files

- format/binary.md
I did an oopsie and the bytes were in the wrong order.
> Fix UDim example in binary.md

- README.md
- rbx_xml/src/types/axes.rs
- rbx_xml/src/types/mod.rs
> rbx_xml Implement Axes

- README.md
- format/binary.md
- rbx_binary/src/deserializer.rs
- rbx_binary/src/serializer.rs
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-unique-parts__decoded.snap
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-unique-parts__encoded.snap
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__three-unique-parts__input.snap
- rbx_binary/src/text_deserializer.rs
Implements `PhysicalProperties` and updates the test files module.
> Implement PhysicalProperties in rbx_binary

- README.md
- format/binary.md
- rbx_binary/src/deserializer.rs
- rbx_binary/src/serializer.rs
- rbx_binary/src/tests/models.rs
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__two-imagebuttons__decoded.snap
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__two-imagebuttons__encoded.snap
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__two-imagebuttons__input.snap
- rbx_binary/src/text_deserializer.rs
Implements and documents `Rect` in the binary format.
> Implement Rect

- rbx_binary/src/serializer.rs
This PR collects together two members from `BinarySerializer` into a new struct. It's intended to help overcome some of the aliasing borrow issues encountered in #142.
This is a common technique in Rust: when a method borrows too much of a struct and it starts being prohibitive, we break out the borrowed parts into a new struct. Usually, this isn't so bad, like in this case. In some gnarlier cases, it can help to make the function in question a free function that takes many independent references.
> Break type_infos member into new struct, TypeInfos

- README.md
- rbx_binary/src/cframe.rs
- rbx_binary/src/deserializer.rs
- rbx_binary/src/lib.rs
- rbx_binary/src/serializer.rs
- rbx_binary/src/text_deserializer.rs
- rbx_types/Cargo.toml
- rbx_types/src/basic_types.rs
> Write CFrame basic rotation IDs

- generate_reflection/src/reflection_types.rs
- rbx_dom_lua/src/ReflectionDatabase/classes.lua
- rbx_reflection/CHANGELOG.md
- rbx_reflection/src/reflection_database/classes.rs
- rbx_reflection/src/reflection_database/enums.rs
- rbx_reflection/src/reflection_database/version.rs
>  Fix rbx-dom v1 generate_reflection reflecting Int64 properties as Int32

- format/binary.md
This PR cleans up inconsistent formatting across the document and renames various chunk fields for (hopefully) increased clarity.
> Refresh the binary format specification

- rbx_types/src/shared_string.rs
- rbx_xml/src/serializer.rs
- rbx_xml/tests/snapshots/test_files__union.snap
- rbx_xml/tests/test-files.rs
> Use BTreeMap for rbx_xml shared string dictionary

- README.md
> Update readme to reflect new MSRV

- docs/binary.md
As per Issue #222, I've decided to document UniqueId in preparation for implementing it. 
EDIT: After some feedback in the linked issue, I'm going to go ahead and bite the bullet and document this properly. I would prefer to view UniqueId as a blob but it doesn't make sense unfortunately.
> Document UniqueId in the binary format

- README.md
Looks like we forgot to do this in #248
> Add Font to property coverage table

- README.md
- rbx_binary/CHANGELOG.md
- rbx_binary/src/core.rs
- rbx_binary/src/deserializer/state.rs
- rbx_binary/src/serializer/state.rs
- rbx_binary/src/tests/mod.rs
- rbx_binary/src/tests/places.rs
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__baseplate-566__decoded.snap
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__baseplate-566__encoded.snap
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__baseplate-566__input.snap
- rbx_binary/src/text_deserializer.rs
- rbx_binary/src/types.rs
- rbx_types/CHANGELOG.md
- rbx_types/src/lib.rs
- rbx_types/src/unique_id.rs
- rbx_types/src/variant.rs
- rbx_xml/CHANGELOG.md
- rbx_xml/Cargo.toml
- rbx_xml/src/error.rs
- rbx_xml/src/types/mod.rs
- rbx_xml/src/types/unique_id.rs
- rbx_xml/tests/basic.rs
Repeat of #256 because I managed to mess that one up really badly. See that PR for any history.
~~This may still fail in CI but I'll fix it when it happens.~~ Nevermind I guess. Sometimes all you need to do is be careful, I guess.
> Implement UniqueId

- rbx_binary/CHANGELOG.md
- rbx_types/CHANGELOG.md
- rbx_xml/CHANGELOG.md
Whoops, my PR ended up making the changelogs wrong
> Correct changelogs for UniqueId

- rbx_dom_weak/src/dom.rs
I forgot to document this change in #288!
> Document behavior of none parent for WeakDom::insert

- rbx_reflection_database/CHANGELOG.md
- rbx_xml/CHANGELOG.md
I forgot to add entries to the changelogs in #359 😔
> Update rbx_xml and rbx_reflection_database changelogs

- rbx_types/CHANGELOG.md
- rbx_types/src/attributes/mod.rs
> Add `len` and `is_empty` method to attributes

- rbx_reflector/src/cli/generate.rs
This PR enables ambiguous database reflection deserialization (using [rmpv](https://docs.rs/rmpv/latest/rmpv/) Value) just like it is possible with JSON.
I'm not sure whether the `--human-readable` option name actually fits this usecase as it's just based on the serde serialzer's `is_human_readable` function.
> Add option to serialize human-readable MessagePack in `rbx_reflector`

- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__baseplate-566__decoded.snap
- rbx_binary/src/tests/snapshots/rbx_binary__tests__util__baseplate-566__encoded.snap
My bad, I should've let CI finish. Ha ha.
> Accept new snapshot for test caused by 628 database update

- rbx_dom_lua/src/customProperties.lua
In #440 I copy pasted some code and forgot to change the comparison operator! 🫠
> Use correct comparison for isAttributeNameReserved

- rbx_reflection/CHANGELOG.md
- rbx_reflection/src/database.rs
- rbx_reflection_database/src/lib.rs
Hi, I keep writing this function and thought it could be provided here.  Open to suggestions for the function name and signature!
> rbx_reflection: has_superclass

- aftman.toml
- roblox-patch.yml
- selene.toml
- Selene and StyLua are several versions out of date, so I updated them
- Selene is missing the definition of `Content.none` so I added it
> Fix Luau CI workflow and update tool versions

- rbx_reflection/src/database.rs
I discovered this while writing other code and realized it would apply here.  This has significantly less code for the same functionality.
> Replace SuperClassIter With std::iter::successors

- rbx_binary/Cargo.toml
- rbx_binary/src/chunk.rs
> Swap LZ4 crate to `lz4_flex`

- rbx_dom_weak/src/dom.rs
> Fix elided lifetime lints new in Rust 1.89
